-- K7 MVP active schema
-- Scope: voice audio -> STT -> normalized consultation card -> API lookup.
-- No masking, customer master, permissions, audit log, or counselor allocation in MVP.

CREATE TABLE IF NOT EXISTS calls (
    call_id uuid PRIMARY KEY,
    status text NOT NULL CHECK (status IN ('processing', 'ready', 'failed')),
    source_channel text NOT NULL DEFAULT 'voice' CHECK (source_channel = 'voice'),
    audio_filename text NOT NULL,
    CONSTRAINT calls_audio_filename_not_blank_chk CHECK (btrim(audio_filename) <> ''),
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- 본인인증 완료 여부만 남긴다. 입력한 생년월일 원문은 어디에도 저장하지 않는다
    -- (프로젝트 전체의 마스킹 원칙 — pii_guard.py 등과 동일 기준).
    auth_verified boolean NOT NULL DEFAULT false,
    auth_verified_at timestamptz
);

CREATE TABLE IF NOT EXISTS transcripts (
    transcript_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    call_id uuid NOT NULL UNIQUE REFERENCES calls (call_id) ON DELETE CASCADE,
    transcript_text text NOT NULL CHECK (btrim(transcript_text) <> ''),
    stt_model text NOT NULL,
    CONSTRAINT transcripts_stt_model_not_blank_chk CHECK (btrim(stt_model) <> ''),
    duration_sec numeric(10, 3) NOT NULL DEFAULT 0 CHECK (duration_sec >= 0),
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS consultation_cards (
    call_id uuid PRIMARY KEY REFERENCES calls (call_id) ON DELETE CASCADE,
    schema_version text NOT NULL DEFAULT 'mvp-1.1',
    summary text NOT NULL CHECK (btrim(summary) <> ''),
    business_type text NOT NULL CHECK (btrim(business_type) <> ''),
    department text NOT NULL CHECK (btrim(department) <> ''),
    routing_reason text NOT NULL CHECK (btrim(routing_reason) <> ''),
    incident_risk text NOT NULL DEFAULT 'low' CHECK (incident_risk IN ('low', 'high')),
    risk_reason text,
    routing_confidence numeric(5, 4) CHECK (
        routing_confidence IS NULL OR routing_confidence BETWEEN 0 AND 1
    ),
    emotion_status text NOT NULL DEFAULT 'unavailable'
        CHECK (emotion_status IN ('unavailable', 'completed')),
    emotion_score numeric(5, 2) CHECK (emotion_score IS NULL OR emotion_score BETWEEN 0 AND 100),
    emotion_level text,
    emotion_reason text,
    raw_model_result jsonb NOT NULL DEFAULT '{}'::jsonb,
    raw_emotion_result jsonb NOT NULL DEFAULT '{}'::jsonb,
    briefing_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT consultation_cards_schema_version_chk CHECK (schema_version = 'mvp-1.1'),
    CONSTRAINT consultation_cards_high_risk_reason_chk CHECK (
        incident_risk <> 'high' OR btrim(COALESCE(risk_reason, '')) <> ''
    ),
    CONSTRAINT consultation_cards_unavailable_emotion_chk CHECK (
        emotion_status <> 'unavailable'
        OR (emotion_score IS NULL AND emotion_level IS NULL)
    ),
    CONSTRAINT consultation_cards_available_emotion_chk CHECK (
        emotion_status = 'unavailable'
        OR (emotion_score IS NOT NULL AND btrim(COALESCE(emotion_level, '')) <> '')
    ),
    CONSTRAINT consultation_cards_active_emotion_status_chk CHECK (
        emotion_status IN ('unavailable', 'completed')
    ),
    CONSTRAINT consultation_cards_emotion_level_chk CHECK (
        emotion_level IS NULL OR emotion_level IN ('stable', 'caution', 'elevated')
    ),
    CONSTRAINT consultation_cards_temperature_band_chk CHECK (
        emotion_score IS NULL
        OR (emotion_score <= 33 AND emotion_level = 'stable')
        OR (emotion_score > 33 AND emotion_score <= 66 AND emotion_level = 'caution')
        OR (emotion_score > 66 AND emotion_level = 'elevated')
    )
);

-- Idempotent contract upgrade for databases created with mvp-1.0.
ALTER TABLE consultation_cards
    DROP CONSTRAINT IF EXISTS consultation_cards_schema_version_chk;
ALTER TABLE consultation_cards
    ALTER COLUMN schema_version SET DEFAULT 'mvp-1.1';
UPDATE consultation_cards
SET schema_version = 'mvp-1.1'
WHERE schema_version <> 'mvp-1.1';
ALTER TABLE consultation_cards
    ADD CONSTRAINT consultation_cards_schema_version_chk
    CHECK (schema_version = 'mvp-1.1');

-- Idempotent constraint upgrades for databases created by earlier revisions.
-- revision. CREATE TABLE IF NOT EXISTS alone cannot add new constraints.
DO $migration$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'consultation_cards'
          AND column_name = 'raw_emotion_result'
    ) THEN
        ALTER TABLE consultation_cards
            ADD COLUMN raw_emotion_result jsonb NOT NULL DEFAULT '{}'::jsonb;
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'consultation_cards'
          AND column_name = 'briefing_payload'
    ) THEN
        ALTER TABLE consultation_cards
            ADD COLUMN briefing_payload jsonb NOT NULL DEFAULT '{}'::jsonb;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'consultation_cards_active_emotion_status_chk'
          AND conrelid = 'consultation_cards'::regclass
    ) THEN
        ALTER TABLE consultation_cards
            ADD CONSTRAINT consultation_cards_active_emotion_status_chk
            CHECK (emotion_status IN ('unavailable', 'completed'));
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'calls_audio_filename_not_blank_chk'
          AND conrelid = 'calls'::regclass
    ) THEN
        ALTER TABLE calls ADD CONSTRAINT calls_audio_filename_not_blank_chk
            CHECK (btrim(audio_filename) <> '');
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'transcripts_stt_model_not_blank_chk'
          AND conrelid = 'transcripts'::regclass
    ) THEN
        ALTER TABLE transcripts ADD CONSTRAINT transcripts_stt_model_not_blank_chk
            CHECK (btrim(stt_model) <> '');
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'consultation_cards_available_emotion_chk'
          AND conrelid = 'consultation_cards'::regclass
    ) THEN
        ALTER TABLE consultation_cards ADD CONSTRAINT consultation_cards_available_emotion_chk
            CHECK (
                emotion_status = 'unavailable'
                OR (emotion_score IS NOT NULL AND btrim(COALESCE(emotion_level, '')) <> '')
            );
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'consultation_cards_emotion_level_chk'
          AND conrelid = 'consultation_cards'::regclass
    ) THEN
        ALTER TABLE consultation_cards
            ADD CONSTRAINT consultation_cards_emotion_level_chk
            CHECK (
                emotion_level IS NULL
                OR emotion_level IN ('stable', 'caution', 'elevated')
            );
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'consultation_cards_temperature_band_chk'
          AND conrelid = 'consultation_cards'::regclass
    ) THEN
        ALTER TABLE consultation_cards
            ADD CONSTRAINT consultation_cards_temperature_band_chk
            CHECK (
                emotion_score IS NULL
                OR (emotion_score <= 33 AND emotion_level = 'stable')
                OR (
                    emotion_score > 33
                    AND emotion_score <= 66
                    AND emotion_level = 'caution'
                )
                OR (emotion_score > 66 AND emotion_level = 'elevated')
            );
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'calls'
          AND column_name = 'auth_verified'
    ) THEN
        ALTER TABLE calls ADD COLUMN auth_verified boolean NOT NULL DEFAULT false;
        ALTER TABLE calls ADD COLUMN auth_verified_at timestamptz;
    END IF;
END
$migration$;

CREATE INDEX IF NOT EXISTS calls_created_at_idx ON calls (created_at DESC);
CREATE INDEX IF NOT EXISTS consultation_cards_department_idx ON consultation_cards (department);
CREATE INDEX IF NOT EXISTS consultation_cards_incident_risk_idx ON consultation_cards (incident_risk);
