-- K7 MVP active schema
-- Scope: voice audio -> STT -> normalized consultation card -> API lookup.
-- No masking, customer master, permissions, audit log, or counselor allocation in MVP.

CREATE TABLE IF NOT EXISTS calls (
    call_id uuid PRIMARY KEY,
    status text NOT NULL CHECK (status IN ('processing', 'ready', 'failed')),
    source_channel text NOT NULL DEFAULT 'voice' CHECK (source_channel = 'voice'),
    audio_filename text NOT NULL,
    CONSTRAINT calls_audio_filename_not_blank_chk CHECK (btrim(audio_filename) <> ''),
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS transcripts (
    transcript_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    call_id uuid NOT NULL UNIQUE REFERENCES calls (call_id) ON DELETE CASCADE,
    transcript_text text NOT NULL CHECK (btrim(transcript_text) <> ''),
    stt_model text NOT NULL,
    CONSTRAINT transcripts_stt_model_not_blank_chk CHECK (btrim(stt_model) <> ''),
    duration_sec numeric(10, 3) NOT NULL DEFAULT 0 CHECK (duration_sec >= 0),
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS consultation_cards (
    call_id uuid PRIMARY KEY REFERENCES calls (call_id) ON DELETE CASCADE,
    schema_version text NOT NULL DEFAULT 'mvp-1.0',
    summary text NOT NULL CHECK (btrim(summary) <> ''),
    business_type text NOT NULL CHECK (btrim(business_type) <> ''),
    department text NOT NULL CHECK (btrim(department) <> ''),
    routing_reason text NOT NULL CHECK (btrim(routing_reason) <> ''),
    incident_risk text NOT NULL DEFAULT 'low' CHECK (incident_risk IN ('low', 'high')),
    risk_reason text,
    routing_confidence numeric(5, 4) CHECK (
        routing_confidence IS NULL OR routing_confidence BETWEEN 0 AND 1
    ),
    emotion_status text NOT NULL DEFAULT 'unavailable'
        CHECK (emotion_status IN ('unavailable', 'demo', 'completed')),
    emotion_score numeric(5, 2) CHECK (emotion_score IS NULL OR emotion_score BETWEEN 0 AND 100),
    emotion_level text,
    emotion_reason text,
    raw_model_result jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT consultation_cards_schema_version_chk CHECK (schema_version = 'mvp-1.0'),
    CONSTRAINT consultation_cards_high_risk_reason_chk CHECK (
        incident_risk <> 'high' OR btrim(COALESCE(risk_reason, '')) <> ''
    ),
    CONSTRAINT consultation_cards_unavailable_emotion_chk CHECK (
        emotion_status <> 'unavailable'
        OR (emotion_score IS NULL AND emotion_level IS NULL)
    ),
    CONSTRAINT consultation_cards_available_emotion_chk CHECK (
        emotion_status = 'unavailable'
        OR (emotion_score IS NOT NULL AND btrim(COALESCE(emotion_level, '')) <> '')
    )
);

-- Idempotent constraint upgrades for a database created by an earlier mvp-1.0
-- revision. CREATE TABLE IF NOT EXISTS alone cannot add new constraints.
DO $migration$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'calls_audio_filename_not_blank_chk'
          AND conrelid = 'calls'::regclass
    ) THEN
        ALTER TABLE calls ADD CONSTRAINT calls_audio_filename_not_blank_chk
            CHECK (btrim(audio_filename) <> '');
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'transcripts_stt_model_not_blank_chk'
          AND conrelid = 'transcripts'::regclass
    ) THEN
        ALTER TABLE transcripts ADD CONSTRAINT transcripts_stt_model_not_blank_chk
            CHECK (btrim(stt_model) <> '');
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'consultation_cards_schema_version_chk'
          AND conrelid = 'consultation_cards'::regclass
    ) THEN
        ALTER TABLE consultation_cards ADD CONSTRAINT consultation_cards_schema_version_chk
            CHECK (schema_version = 'mvp-1.0');
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'consultation_cards_available_emotion_chk'
          AND conrelid = 'consultation_cards'::regclass
    ) THEN
        ALTER TABLE consultation_cards ADD CONSTRAINT consultation_cards_available_emotion_chk
            CHECK (
                emotion_status = 'unavailable'
                OR (emotion_score IS NOT NULL AND btrim(COALESCE(emotion_level, '')) <> '')
            );
    END IF;
END
$migration$;

CREATE INDEX IF NOT EXISTS calls_created_at_idx ON calls (created_at DESC);
CREATE INDEX IF NOT EXISTS consultation_cards_department_idx ON consultation_cards (department);
CREATE INDEX IF NOT EXISTS consultation_cards_incident_risk_idx ON consultation_cards (incident_risk);
