-- LEGACY REFERENCE ONLY: Railway mvp-1.0 DB에 적용하지 않는다.
-- 활성 스키마: database/mvp/schema.sql
-- KDA K7 상담 사전카드 서비스 PostgreSQL 스키마
-- 실행 대상: PostgreSQL 15 이상

BEGIN;

CREATE TABLE departments (
    department_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_code text NOT NULL UNIQUE,
    department_name text NOT NULL UNIQUE,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT departments_code_format_chk
        CHECK (department_code ~ '^[a-z][a-z0-9_]*$'),
    CONSTRAINT departments_name_not_blank_chk
        CHECK (btrim(department_name) <> '')
);

CREATE TABLE customers (
    customer_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_number text NOT NULL UNIQUE,
    full_name_masked text NOT NULL,
    phone_masked text NOT NULL,
    phone_lookup_hash text NOT NULL UNIQUE,
    account_number_masked text,
    account_lookup_hash text UNIQUE,
    birth_year smallint,
    birth_date_masked text,
    customer_status text NOT NULL DEFAULT 'active',
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT customers_number_format_chk
        CHECK (customer_number ~ '^[A-Z0-9_-]{6,30}$'),
    CONSTRAINT customers_name_masked_chk
        CHECK (btrim(full_name_masked) <> '' AND position('*' IN full_name_masked) > 0),
    CONSTRAINT customers_phone_masked_chk
        CHECK (position('*' IN phone_masked) > 0),
    CONSTRAINT customers_phone_hash_chk
        CHECK (phone_lookup_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT customers_account_pair_chk
        CHECK (
            (account_number_masked IS NULL AND account_lookup_hash IS NULL)
            OR (
                account_number_masked IS NOT NULL
                AND account_lookup_hash IS NOT NULL
                AND position('*' IN account_number_masked) > 0
                AND account_lookup_hash ~ '^[0-9a-f]{64}$'
            )
        ),
    CONSTRAINT customers_birth_year_chk
        CHECK (birth_year IS NULL OR birth_year BETWEEN 1900 AND 2100),
    CONSTRAINT customers_birth_date_masked_chk
        CHECK (birth_date_masked IS NULL OR position('*' IN birth_date_masked) > 0),
    CONSTRAINT customers_status_chk
        CHECK (customer_status IN ('active', 'inactive', 'dormant'))
);

CREATE TABLE counselors (
    counselor_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    counselor_code text NOT NULL UNIQUE,
    counselor_name text NOT NULL,
    department_id bigint NOT NULL,
    employment_status text NOT NULL DEFAULT 'active',
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT counselors_department_fk
        FOREIGN KEY (department_id) REFERENCES departments (department_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT counselors_code_format_chk
        CHECK (counselor_code ~ '^[A-Z0-9_-]{4,30}$'),
    CONSTRAINT counselors_name_not_blank_chk
        CHECK (btrim(counselor_name) <> ''),
    CONSTRAINT counselors_status_chk
        CHECK (employment_status IN ('active', 'leave', 'inactive')),
    CONSTRAINT counselors_id_department_uk
        UNIQUE (counselor_id, department_id)
);

CREATE TABLE counselor_permissions (
    permission_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    counselor_id bigint NOT NULL,
    permission_scope text NOT NULL,
    access_level text NOT NULL,
    granted_reason text NOT NULL,
    granted_by bigint,
    valid_from timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    valid_until timestamptz,
    revoked_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT counselor_permissions_counselor_fk
        FOREIGN KEY (counselor_id) REFERENCES counselors (counselor_id)
        ON UPDATE RESTRICT ON DELETE CASCADE,
    CONSTRAINT counselor_permissions_granted_by_fk
        FOREIGN KEY (granted_by) REFERENCES counselors (counselor_id)
        ON UPDATE RESTRICT ON DELETE SET NULL,
    CONSTRAINT counselor_permissions_scope_chk
        CHECK (permission_scope IN (
            'customer_basic',
            'consultation_history',
            'customer_cautions',
            'utterances',
            'model_analysis_results',
            'ai_consultation_cards',
            'routing_recommendations',
            'access_logs'
        )),
    CONSTRAINT counselor_permissions_level_chk
        CHECK (access_level IN ('masked_read', 'read', 'manage')),
    CONSTRAINT counselor_permissions_reason_not_blank_chk
        CHECK (btrim(granted_reason) <> ''),
    CONSTRAINT counselor_permissions_valid_period_chk
        CHECK (valid_until IS NULL OR valid_until > valid_from),
    CONSTRAINT counselor_permissions_revoke_chk
        CHECK (revoked_at IS NULL OR revoked_at >= valid_from)
);

CREATE TABLE consultation_sessions (
    session_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_session_key text NOT NULL UNIQUE,
    customer_id bigint NOT NULL,
    assigned_counselor_id bigint,
    inquiry_type text NOT NULL DEFAULT 'unclassified',
    session_status text NOT NULL DEFAULT 'waiting',
    channel text NOT NULL DEFAULT 'voice',
    risk_level text NOT NULL DEFAULT 'low',
    consent_to_record boolean NOT NULL DEFAULT false,
    started_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ended_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT consultation_sessions_customer_fk
        FOREIGN KEY (customer_id) REFERENCES customers (customer_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT consultation_sessions_counselor_fk
        FOREIGN KEY (assigned_counselor_id) REFERENCES counselors (counselor_id)
        ON UPDATE RESTRICT ON DELETE SET NULL,
    CONSTRAINT consultation_sessions_external_key_length_chk
        CHECK (char_length(btrim(external_session_key)) BETWEEN 1 AND 100),
    CONSTRAINT consultation_sessions_inquiry_type_chk
        CHECK (inquiry_type IN (
            'unclassified',
            'mistaken_transfer',
            'voice_phishing_suspected',
            'lost_card',
            'overseas_payment',
            'account_opening',
            'payment_error',
            'loan',
            'general_inquiry',
            'other'
        )),
    CONSTRAINT consultation_sessions_status_chk
        CHECK (session_status IN (
            'waiting',
            'analyzing',
            'ready',
            'in_progress',
            'summarizing',
            'wrap_up',
            'completed',
            'cancelled'
        )),
    CONSTRAINT consultation_sessions_channel_chk
        CHECK (channel IN ('voice', 'chat', 'web')),
    CONSTRAINT consultation_sessions_risk_chk
        CHECK (risk_level IN ('low', 'medium', 'high', 'critical')),
    CONSTRAINT consultation_sessions_period_chk
        CHECK (ended_at IS NULL OR ended_at >= started_at),
    CONSTRAINT consultation_sessions_id_customer_uk
        UNIQUE (session_id, customer_id)
);

CREATE TABLE utterances (
    utterance_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id bigint NOT NULL,
    speaker_type text NOT NULL,
    sequence_no integer NOT NULL,
    transcript_ciphertext bytea,
    encryption_key_version text,
    masked_transcript text NOT NULL,
    contains_sensitive_data boolean NOT NULL DEFAULT false,
    stt_confidence numeric(5,4),
    spoken_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT utterances_session_fk
        FOREIGN KEY (session_id) REFERENCES consultation_sessions (session_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT utterances_speaker_chk
        CHECK (speaker_type IN ('customer', 'system', 'counselor')),
    CONSTRAINT utterances_sequence_chk
        CHECK (sequence_no > 0),
    CONSTRAINT utterances_masked_not_blank_chk
        CHECK (btrim(masked_transcript) <> ''),
    CONSTRAINT utterances_ciphertext_pair_chk
        CHECK (
            (transcript_ciphertext IS NULL AND encryption_key_version IS NULL)
            OR (transcript_ciphertext IS NOT NULL AND encryption_key_version IS NOT NULL)
        ),
    CONSTRAINT utterances_stt_confidence_chk
        CHECK (stt_confidence IS NULL OR stt_confidence BETWEEN 0 AND 1),
    CONSTRAINT utterances_session_sequence_uk
        UNIQUE (session_id, sequence_no)
);

CREATE TABLE model_analysis_results (
    analysis_result_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id bigint NOT NULL,
    result_key text NOT NULL UNIQUE,
    model_name text NOT NULL,
    model_version text NOT NULL,
    output_schema_version text NOT NULL DEFAULT '1.0',
    analysis_status text NOT NULL DEFAULT 'completed',
    emotion_temperature_score numeric(5,2),
    emotion_temperature_level text,
    voice_arousal_score numeric(5,2),
    voice_dominance_score numeric(5,2),
    voice_valence_score numeric(5,2),
    negative_activation_score numeric(5,2),
    audio_quality text NOT NULL,
    failure_code text,
    generated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT model_analysis_results_session_fk
        FOREIGN KEY (session_id) REFERENCES consultation_sessions (session_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT model_analysis_results_result_key_length_chk
        CHECK (char_length(btrim(result_key)) BETWEEN 1 AND 100),
    CONSTRAINT model_analysis_results_model_length_chk
        CHECK (
            char_length(btrim(model_name)) BETWEEN 1 AND 100
            AND char_length(btrim(model_version)) BETWEEN 1 AND 50
        ),
    CONSTRAINT model_analysis_results_schema_version_chk
        CHECK (output_schema_version ~ '^[0-9]+\.[0-9]+$'),
    CONSTRAINT model_analysis_results_status_chk
        CHECK (analysis_status IN ('completed', 'unavailable', 'failed')),
    CONSTRAINT model_analysis_results_temperature_score_chk
        CHECK (
            emotion_temperature_score IS NULL
            OR emotion_temperature_score BETWEEN 0 AND 100
        ),
    CONSTRAINT model_analysis_results_temperature_level_chk
        CHECK (
            emotion_temperature_level IS NULL
            OR emotion_temperature_level IN ('stable', 'caution', 'elevated')
        ),
    CONSTRAINT model_analysis_results_completed_payload_chk
        CHECK (
            (
                analysis_status = 'completed'
                AND emotion_temperature_score IS NOT NULL
                AND emotion_temperature_level IS NOT NULL
                AND failure_code IS NULL
            )
            OR (
                analysis_status IN ('unavailable', 'failed')
                AND emotion_temperature_score IS NULL
                AND emotion_temperature_level IS NULL
                AND voice_arousal_score IS NULL
                AND voice_dominance_score IS NULL
                AND voice_valence_score IS NULL
                AND negative_activation_score IS NULL
                AND char_length(btrim(failure_code)) BETWEEN 1 AND 100
            )
        ),
    CONSTRAINT model_analysis_results_temperature_pair_chk
        CHECK (
            analysis_status <> 'completed'
            OR (emotion_temperature_score <= 33 AND emotion_temperature_level = 'stable')
            OR (
                emotion_temperature_score > 33
                AND emotion_temperature_score <= 66
                AND emotion_temperature_level = 'caution'
            )
            OR (emotion_temperature_score > 66 AND emotion_temperature_level = 'elevated')
        ),
    CONSTRAINT model_analysis_results_arousal_chk
        CHECK (voice_arousal_score IS NULL OR voice_arousal_score BETWEEN 0 AND 100),
    CONSTRAINT model_analysis_results_dominance_chk
        CHECK (voice_dominance_score IS NULL OR voice_dominance_score BETWEEN 0 AND 100),
    CONSTRAINT model_analysis_results_valence_chk
        CHECK (voice_valence_score IS NULL OR voice_valence_score BETWEEN 0 AND 100),
    CONSTRAINT model_analysis_results_negative_activation_chk
        CHECK (negative_activation_score IS NULL OR negative_activation_score BETWEEN 0 AND 100),
    CONSTRAINT model_analysis_results_audio_quality_chk
        CHECK (audio_quality IN ('normal', 'low_volume', 'noisy', 'too_short', 'unavailable')),
    CONSTRAINT model_analysis_results_id_session_uk
        UNIQUE (analysis_result_id, session_id),
    CONSTRAINT model_analysis_results_version_generated_uk
        UNIQUE (session_id, model_name, model_version, generated_at)
);

CREATE TABLE ai_consultation_cards (
    card_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id bigint NOT NULL UNIQUE,
    analysis_result_id bigint,
    card_schema_version text NOT NULL DEFAULT '1.0',
    summary text NOT NULL,
    customer_request text,
    keywords text[] NOT NULL DEFAULT ARRAY[]::text[],
    risk_factors text[] NOT NULL DEFAULT ARRAY[]::text[],
    urgency_level text NOT NULL,
    risk_level text NOT NULL,
    related_manual_refs text[] NOT NULL DEFAULT ARRAY[]::text[],
    suggested_opening text,
    recommended_actions text[] NOT NULL DEFAULT ARRAY[]::text[],
    confirmation_items text[] NOT NULL DEFAULT ARRAY[]::text[],
    confirmation_status text NOT NULL DEFAULT 'pending',
    confirmed_at timestamptz,
    model_name text NOT NULL,
    model_version text NOT NULL,
    generated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ai_consultation_cards_session_fk
        FOREIGN KEY (session_id) REFERENCES consultation_sessions (session_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT ai_consultation_cards_analysis_result_fk
        FOREIGN KEY (analysis_result_id, session_id)
        REFERENCES model_analysis_results (analysis_result_id, session_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT ai_consultation_cards_schema_version_chk
        CHECK (card_schema_version ~ '^[0-9]+\.[0-9]+$'),
    CONSTRAINT ai_consultation_cards_summary_not_blank_chk
        CHECK (btrim(summary) <> ''),
    CONSTRAINT ai_consultation_cards_customer_request_chk
        CHECK (customer_request IS NULL OR btrim(customer_request) <> ''),
    CONSTRAINT ai_consultation_cards_urgency_chk
        CHECK (urgency_level IN ('low', 'medium', 'high', 'critical')),
    CONSTRAINT ai_consultation_cards_risk_chk
        CHECK (risk_level IN ('low', 'medium', 'high', 'critical')),
    CONSTRAINT ai_consultation_cards_confirmation_status_chk
        CHECK (confirmation_status IN ('pending', 'confirmed', 'correction_requested')),
    CONSTRAINT ai_consultation_cards_confirmation_time_chk
        CHECK (
            (confirmation_status = 'confirmed' AND confirmed_at IS NOT NULL)
            OR (confirmation_status <> 'confirmed' AND confirmed_at IS NULL)
        ),
    CONSTRAINT ai_consultation_cards_model_not_blank_chk
        CHECK (btrim(model_name) <> '' AND btrim(model_version) <> '')
);

CREATE TABLE consultation_history (
    history_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id bigint NOT NULL,
    source_session_id bigint UNIQUE,
    counselor_id bigint,
    inquiry_type text NOT NULL,
    ai_summary text NOT NULL,
    resolution_result text NOT NULL,
    department_id bigint NOT NULL,
    risk_level text NOT NULL,
    consulted_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT consultation_history_customer_fk
        FOREIGN KEY (customer_id) REFERENCES customers (customer_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT consultation_history_session_fk
        FOREIGN KEY (source_session_id) REFERENCES consultation_sessions (session_id)
        ON UPDATE RESTRICT ON DELETE SET NULL,
    CONSTRAINT consultation_history_counselor_fk
        FOREIGN KEY (counselor_id) REFERENCES counselors (counselor_id)
        ON UPDATE RESTRICT ON DELETE SET NULL,
    CONSTRAINT consultation_history_department_fk
        FOREIGN KEY (department_id) REFERENCES departments (department_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT consultation_history_inquiry_type_chk
        CHECK (inquiry_type IN (
            'mistaken_transfer',
            'voice_phishing_suspected',
            'lost_card',
            'overseas_payment',
            'account_opening',
            'payment_error',
            'loan',
            'general_inquiry',
            'other'
        )),
    CONSTRAINT consultation_history_summary_not_blank_chk
        CHECK (btrim(ai_summary) <> ''),
    CONSTRAINT consultation_history_result_not_blank_chk
        CHECK (btrim(resolution_result) <> ''),
    CONSTRAINT consultation_history_risk_chk
        CHECK (risk_level IN ('low', 'medium', 'high', 'critical'))
);

CREATE TABLE customer_cautions (
    caution_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id bigint NOT NULL,
    caution_type text NOT NULL,
    reason text NOT NULL,
    severity text NOT NULL,
    caution_status text NOT NULL DEFAULT 'active',
    registered_by bigint,
    registered_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT customer_cautions_customer_fk
        FOREIGN KEY (customer_id) REFERENCES customers (customer_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT customer_cautions_registered_by_fk
        FOREIGN KEY (registered_by) REFERENCES counselors (counselor_id)
        ON UPDATE RESTRICT ON DELETE SET NULL,
    CONSTRAINT customer_cautions_type_chk
        CHECK (caution_type IN (
            'fraud_suspected',
            'abusive_behavior',
            'repeated_dispute',
            'additional_review_required',
            'vulnerable_customer',
            'other'
        )),
    CONSTRAINT customer_cautions_reason_not_blank_chk
        CHECK (btrim(reason) <> ''),
    CONSTRAINT customer_cautions_severity_chk
        CHECK (severity IN ('low', 'medium', 'high', 'critical')),
    CONSTRAINT customer_cautions_status_chk
        CHECK (caution_status IN ('active', 'expired', 'revoked')),
    CONSTRAINT customer_cautions_expiry_chk
        CHECK (expires_at IS NULL OR expires_at > registered_at)
);

CREATE TABLE routing_recommendations (
    routing_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id bigint NOT NULL,
    recommended_department_id bigint NOT NULL,
    recommended_counselor_id bigint,
    recommendation_rank smallint NOT NULL,
    confidence numeric(5,4) NOT NULL,
    rationale text NOT NULL,
    selected boolean NOT NULL DEFAULT false,
    model_name text NOT NULL,
    model_version text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT routing_recommendations_session_fk
        FOREIGN KEY (session_id) REFERENCES consultation_sessions (session_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT routing_recommendations_department_fk
        FOREIGN KEY (recommended_department_id) REFERENCES departments (department_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT routing_recommendations_counselor_department_fk
        FOREIGN KEY (recommended_counselor_id, recommended_department_id)
        REFERENCES counselors (counselor_id, department_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT routing_recommendations_rank_chk
        CHECK (recommendation_rank > 0),
    CONSTRAINT routing_recommendations_confidence_chk
        CHECK (confidence BETWEEN 0 AND 1),
    CONSTRAINT routing_recommendations_rationale_not_blank_chk
        CHECK (btrim(rationale) <> ''),
    CONSTRAINT routing_recommendations_model_not_blank_chk
        CHECK (btrim(model_name) <> '' AND btrim(model_version) <> ''),
    CONSTRAINT routing_recommendations_session_rank_uk
        UNIQUE (session_id, recommendation_rank)
);

CREATE TABLE access_logs (
    access_log_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    counselor_id bigint NOT NULL,
    customer_id bigint NOT NULL,
    session_id bigint,
    information_scope text NOT NULL,
    action_type text NOT NULL DEFAULT 'view',
    access_purpose text NOT NULL,
    result_status text NOT NULL DEFAULT 'success',
    request_id text,
    source_ip inet,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT access_logs_counselor_fk
        FOREIGN KEY (counselor_id) REFERENCES counselors (counselor_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT access_logs_customer_fk
        FOREIGN KEY (customer_id) REFERENCES customers (customer_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT access_logs_session_customer_fk
        FOREIGN KEY (session_id, customer_id)
        REFERENCES consultation_sessions (session_id, customer_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT access_logs_scope_chk
        CHECK (information_scope IN (
            'customer_basic',
            'consultation_history',
            'customer_cautions',
            'utterances',
            'model_analysis_results',
            'ai_consultation_cards',
            'routing_recommendations'
        )),
    CONSTRAINT access_logs_action_chk
        CHECK (action_type IN ('view', 'export', 'create', 'update')),
    CONSTRAINT access_logs_purpose_not_blank_chk
        CHECK (btrim(access_purpose) <> ''),
    CONSTRAINT access_logs_result_chk
        CHECK (result_status IN ('success', 'denied', 'error')),
    CONSTRAINT access_logs_immutable_timestamps_chk
        CHECK (updated_at = created_at)
);

-- 주요 조회 경로 및 외래키 인덱스
CREATE INDEX idx_customers_created_at
    ON customers (created_at DESC);

CREATE INDEX idx_counselors_department_id
    ON counselors (department_id);

CREATE INDEX idx_counselor_permissions_granted_by
    ON counselor_permissions (granted_by)
    WHERE granted_by IS NOT NULL;

CREATE UNIQUE INDEX uq_counselor_permissions_active_scope
    ON counselor_permissions (counselor_id, permission_scope)
    WHERE revoked_at IS NULL;

CREATE INDEX idx_consultation_sessions_customer_created
    ON consultation_sessions (customer_id, created_at DESC);

CREATE INDEX idx_consultation_sessions_counselor_status
    ON consultation_sessions (assigned_counselor_id, session_status)
    WHERE assigned_counselor_id IS NOT NULL;

CREATE INDEX idx_consultation_sessions_status_created
    ON consultation_sessions (session_status, created_at DESC);

CREATE INDEX idx_utterances_session_spoken
    ON utterances (session_id, spoken_at);

CREATE INDEX idx_model_analysis_results_session_generated
    ON model_analysis_results (session_id, generated_at DESC);

CREATE INDEX idx_model_analysis_results_temperature_generated
    ON model_analysis_results (emotion_temperature_level, generated_at DESC);

CREATE INDEX idx_ai_cards_analysis_result_session
    ON ai_consultation_cards (analysis_result_id, session_id)
    WHERE analysis_result_id IS NOT NULL;

CREATE INDEX idx_ai_cards_risk_generated
    ON ai_consultation_cards (risk_level, generated_at DESC);

CREATE INDEX idx_consultation_history_customer_consulted
    ON consultation_history (customer_id, consulted_at DESC);

CREATE INDEX idx_consultation_history_counselor_consulted
    ON consultation_history (counselor_id, consulted_at DESC)
    WHERE counselor_id IS NOT NULL;

CREATE INDEX idx_consultation_history_department_consulted
    ON consultation_history (department_id, consulted_at DESC);

CREATE INDEX idx_consultation_history_inquiry_consulted
    ON consultation_history (inquiry_type, consulted_at DESC);

CREATE INDEX idx_consultation_history_high_risk
    ON consultation_history (consulted_at DESC)
    WHERE risk_level IN ('high', 'critical');

CREATE INDEX idx_customer_cautions_customer_status
    ON customer_cautions (customer_id, caution_status, registered_at DESC);

CREATE INDEX idx_customer_cautions_registered_by
    ON customer_cautions (registered_by)
    WHERE registered_by IS NOT NULL;

CREATE INDEX idx_routing_recommendations_session_confidence
    ON routing_recommendations (session_id, confidence DESC);

CREATE INDEX idx_routing_recommendations_department
    ON routing_recommendations (recommended_department_id, created_at DESC);

CREATE INDEX idx_routing_recommendations_counselor
    ON routing_recommendations (
        recommended_counselor_id,
        recommended_department_id,
        created_at DESC
    )
    WHERE recommended_counselor_id IS NOT NULL;

CREATE UNIQUE INDEX uq_routing_recommendations_selected_session
    ON routing_recommendations (session_id)
    WHERE selected;

CREATE INDEX idx_access_logs_customer_created
    ON access_logs (customer_id, created_at DESC);

CREATE INDEX idx_access_logs_counselor_created
    ON access_logs (counselor_id, created_at DESC);

CREATE INDEX idx_access_logs_session_created
    ON access_logs (session_id, customer_id, created_at DESC)
    WHERE session_id IS NOT NULL;

CREATE INDEX idx_access_logs_request_id
    ON access_logs (request_id)
    WHERE request_id IS NOT NULL;

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_departments_updated_at
BEFORE UPDATE ON departments
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_customers_updated_at
BEFORE UPDATE ON customers
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_counselors_updated_at
BEFORE UPDATE ON counselors
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_counselor_permissions_updated_at
BEFORE UPDATE ON counselor_permissions
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_consultation_sessions_updated_at
BEFORE UPDATE ON consultation_sessions
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- 녹취 미동의 세션에는 발화 원문 암호문도 저장하지 않는다.
CREATE OR REPLACE FUNCTION enforce_utterance_recording_consent()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.transcript_ciphertext IS NOT NULL
       AND NOT EXISTS (
           SELECT 1
           FROM consultation_sessions AS s
           WHERE s.session_id = NEW.session_id
             AND s.consent_to_record
       ) THEN
        RAISE EXCEPTION 'encrypted transcript requires recording consent'
            USING ERRCODE = '23514';
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_utterances_recording_consent
BEFORE INSERT OR UPDATE OF session_id, transcript_ciphertext ON utterances
FOR EACH ROW EXECUTE FUNCTION enforce_utterance_recording_consent();

CREATE TRIGGER trg_utterances_updated_at
BEFORE UPDATE ON utterances
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_model_analysis_results_updated_at
BEFORE UPDATE ON model_analysis_results
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_ai_consultation_cards_updated_at
BEFORE UPDATE ON ai_consultation_cards
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_consultation_history_updated_at
BEFORE UPDATE ON consultation_history
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_customer_cautions_updated_at
BEFORE UPDATE ON customer_cautions
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_routing_recommendations_updated_at
BEFORE UPDATE ON routing_recommendations
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- 감사로그는 생성 후 변경·삭제할 수 없도록 한다.
CREATE OR REPLACE FUNCTION prevent_access_log_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'access_logs rows are immutable';
END;
$$;

CREATE TRIGGER trg_access_logs_immutable
BEFORE UPDATE OR DELETE ON access_logs
FOR EACH ROW EXECUTE FUNCTION prevent_access_log_mutation();

COMMIT;
